# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chinese_aster/protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Chinese_aster.protos.feature_extractor_pb2
import Chinese_aster.protos.predictor_pb2
import Chinese_aster.protos.spatial_transformer_pb2
import Chinese_aster.protos.loss_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Chinese_aster/protos/model.proto',
  package='Chinese_aster.protos',
  serialized_pb=_b('\n Chinese_aster/protos/model.proto\x12\x14\x43hinese_aster.protos\x1a,Chinese_aster/protos/feature_extractor.proto\x1a$Chinese_aster/protos/predictor.proto\x1a.Chinese_aster/protos/spatial_transformer.proto\x1a\x1f\x43hinese_aster/protos/loss.proto\"{\n\x05Model\x12\x63\n\"multi_predictors_recognition_model\x18\x01 \x01(\x0b\x32\x35.Chinese_aster.protos.MultiPredictorsRecognitionModelH\x00\x42\r\n\x0bmodel_oneof\"\xb9\x02\n\x1fMultiPredictorsRecognitionModel\x12\x45\n\x13spatial_transformer\x18\x01 \x01(\x0b\x32(.Chinese_aster.protos.SpatialTransformer\x12\x41\n\x11\x66\x65\x61ture_extractor\x18\x02 \x01(\x0b\x32&.Chinese_aster.protos.FeatureExtractor\x12\x32\n\tpredictor\x18\x03 \x03(\x0b\x32\x1f.Chinese_aster.protos.Predictor\x12#\n\x14keypoint_supervision\x18\x04 \x01(\x08:\x05\x66\x61lse\x12\x33\n\x0fregression_loss\x18\x05 \x01(\x0b\x32\x1a.Chinese_aster.protos.Loss')
  ,
  dependencies=[Chinese_aster.protos.feature_extractor_pb2.DESCRIPTOR,Chinese_aster.protos.predictor_pb2.DESCRIPTOR,Chinese_aster.protos.spatial_transformer_pb2.DESCRIPTOR,Chinese_aster.protos.loss_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Chinese_aster.protos.Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_predictors_recognition_model', full_name='Chinese_aster.protos.Model.multi_predictors_recognition_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='model_oneof', full_name='Chinese_aster.protos.Model.model_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=223,
  serialized_end=346,
)


_MULTIPREDICTORSRECOGNITIONMODEL = _descriptor.Descriptor(
  name='MultiPredictorsRecognitionModel',
  full_name='Chinese_aster.protos.MultiPredictorsRecognitionModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='spatial_transformer', full_name='Chinese_aster.protos.MultiPredictorsRecognitionModel.spatial_transformer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='Chinese_aster.protos.MultiPredictorsRecognitionModel.feature_extractor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='predictor', full_name='Chinese_aster.protos.MultiPredictorsRecognitionModel.predictor', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='keypoint_supervision', full_name='Chinese_aster.protos.MultiPredictorsRecognitionModel.keypoint_supervision', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='regression_loss', full_name='Chinese_aster.protos.MultiPredictorsRecognitionModel.regression_loss', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=662,
)

_MODEL.fields_by_name['multi_predictors_recognition_model'].message_type = _MULTIPREDICTORSRECOGNITIONMODEL
_MODEL.oneofs_by_name['model_oneof'].fields.append(
  _MODEL.fields_by_name['multi_predictors_recognition_model'])
_MODEL.fields_by_name['multi_predictors_recognition_model'].containing_oneof = _MODEL.oneofs_by_name['model_oneof']
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['spatial_transformer'].message_type = Chinese_aster.protos.spatial_transformer_pb2._SPATIALTRANSFORMER
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['feature_extractor'].message_type = Chinese_aster.protos.feature_extractor_pb2._FEATUREEXTRACTOR
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['predictor'].message_type = Chinese_aster.protos.predictor_pb2._PREDICTOR
_MULTIPREDICTORSRECOGNITIONMODEL.fields_by_name['regression_loss'].message_type = Chinese_aster.protos.loss_pb2._LOSS
DESCRIPTOR.message_types_by_name['Model'] = _MODEL
DESCRIPTOR.message_types_by_name['MultiPredictorsRecognitionModel'] = _MULTIPREDICTORSRECOGNITIONMODEL

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'Chinese_aster.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:Chinese_aster.protos.Model)
  ))
_sym_db.RegisterMessage(Model)

MultiPredictorsRecognitionModel = _reflection.GeneratedProtocolMessageType('MultiPredictorsRecognitionModel', (_message.Message,), dict(
  DESCRIPTOR = _MULTIPREDICTORSRECOGNITIONMODEL,
  __module__ = 'Chinese_aster.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:Chinese_aster.protos.MultiPredictorsRecognitionModel)
  ))
_sym_db.RegisterMessage(MultiPredictorsRecognitionModel)


# @@protoc_insertion_point(module_scope)
