# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Chinese_aster/protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Chinese_aster.protos.train_pb2
import Chinese_aster.protos.eval_pb2
import Chinese_aster.protos.input_reader_pb2
import Chinese_aster.protos.model_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Chinese_aster/protos/pipeline.proto',
  package='Chinese_aster.protos',
  serialized_pb=_b('\n#Chinese_aster/protos/pipeline.proto\x12\x14\x43hinese_aster.protos\x1a Chinese_aster/protos/train.proto\x1a\x1f\x43hinese_aster/protos/eval.proto\x1a\'Chinese_aster/protos/input_reader.proto\x1a Chinese_aster/protos/model.proto\"\xb2\x02\n\x17TrainEvalPipelineConfig\x12*\n\x05model\x18\x01 \x01(\x0b\x32\x1b.Chinese_aster.protos.Model\x12\x37\n\x0ctrain_config\x18\x02 \x01(\x0b\x32!.Chinese_aster.protos.TrainConfig\x12=\n\x12train_input_reader\x18\x03 \x03(\x0b\x32!.Chinese_aster.protos.InputReader\x12\x35\n\x0b\x65val_config\x18\x04 \x01(\x0b\x32 .Chinese_aster.protos.EvalConfig\x12<\n\x11\x65val_input_reader\x18\x05 \x01(\x0b\x32!.Chinese_aster.protos.InputReader')
  ,
  dependencies=[Chinese_aster.protos.train_pb2.DESCRIPTOR,Chinese_aster.protos.eval_pb2.DESCRIPTOR,Chinese_aster.protos.input_reader_pb2.DESCRIPTOR,Chinese_aster.protos.model_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAINEVALPIPELINECONFIG = _descriptor.Descriptor(
  name='TrainEvalPipelineConfig',
  full_name='Chinese_aster.protos.TrainEvalPipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='Chinese_aster.protos.TrainEvalPipelineConfig.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='Chinese_aster.protos.TrainEvalPipelineConfig.train_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_input_reader', full_name='Chinese_aster.protos.TrainEvalPipelineConfig.train_input_reader', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='Chinese_aster.protos.TrainEvalPipelineConfig.eval_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_input_reader', full_name='Chinese_aster.protos.TrainEvalPipelineConfig.eval_input_reader', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=510,
)

_TRAINEVALPIPELINECONFIG.fields_by_name['model'].message_type = Chinese_aster.protos.model_pb2._MODEL
_TRAINEVALPIPELINECONFIG.fields_by_name['train_config'].message_type = Chinese_aster.protos.train_pb2._TRAINCONFIG
_TRAINEVALPIPELINECONFIG.fields_by_name['train_input_reader'].message_type = Chinese_aster.protos.input_reader_pb2._INPUTREADER
_TRAINEVALPIPELINECONFIG.fields_by_name['eval_config'].message_type = Chinese_aster.protos.eval_pb2._EVALCONFIG
_TRAINEVALPIPELINECONFIG.fields_by_name['eval_input_reader'].message_type = Chinese_aster.protos.input_reader_pb2._INPUTREADER
DESCRIPTOR.message_types_by_name['TrainEvalPipelineConfig'] = _TRAINEVALPIPELINECONFIG

TrainEvalPipelineConfig = _reflection.GeneratedProtocolMessageType('TrainEvalPipelineConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINEVALPIPELINECONFIG,
  __module__ = 'Chinese_aster.protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:Chinese_aster.protos.TrainEvalPipelineConfig)
  ))
_sym_db.RegisterMessage(TrainEvalPipelineConfig)


# @@protoc_insertion_point(module_scope)
